export type Competition = "Premier League" | "Champions League" | "FA Cup" | "Carabao Cup";
export type Venue = "home" | "away" | "neutral";
export type Result = "win" | "draw" | "loss";

export type Match = {
  id: string;
  date: string;
  competition: Competition;
  opponent: string;
  venue: Venue;
  goalsFor: number;
  goalsAgainst: number;
  result: Result;
  xG: number;
  xGA: number;
  shots: number;
  shotsOnTarget: number;
  possession: number;
  pressingIntensity: number;
  buildUpQuality: number;
  chanceCreation: number;
  defensiveRisk: number;
  transitionRisk: number;
  setPieceThreat: number;
  matchControl: number;
};

export type Fixture = {
  id: string;
  date: string;
  competition: Competition;
  opponent: string;
  venue: Venue;
  opponentForm: number;
  opponentStrengths: string[];
  opponentWeaknesses: string[];
  matchImportance: "medium" | "high" | "critical";
};

export type PlayerStat = {
  id: string;
  name: string;
  position: "GK" | "DF" | "MF" | "FW";
  appearances: number;
  minutes: number;
  goals: number;
  assists: number;
  xG: number;
  xA: number;
  shots: number;
  keyPasses: number;
  rating: number;
  formTrend: "up" | "flat" | "down";
  injuryStatus: "fit" | "monitor" | "injured";
  pressingActions: number;
  recoveries: number;
};

export const competitions: Competition[] = ["Premier League", "Champions League", "FA Cup", "Carabao Cup"];

export const demoMatches: Match[] = [
  {
    id: "m01",
    date: "2025-08-16",
    competition: "Premier League",
    opponent: "Brighton",
    venue: "home",
    goalsFor: 2,
    goalsAgainst: 1,
    result: "win",
    xG: 1.86,
    xGA: 1.12,
    shots: 15,
    shotsOnTarget: 6,
    possession: 56,
    pressingIntensity: 74,
    buildUpQuality: 70,
    chanceCreation: 76,
    defensiveRisk: 42,
    transitionRisk: 38,
    setPieceThreat: 62,
    matchControl: 68
  },
  {
    id: "m02",
    date: "2025-08-23",
    competition: "Premier League",
    opponent: "Tottenham",
    venue: "away",
    goalsFor: 1,
    goalsAgainst: 2,
    result: "loss",
    xG: 1.24,
    xGA: 1.72,
    shots: 11,
    shotsOnTarget: 4,
    possession: 49,
    pressingIntensity: 66,
    buildUpQuality: 61,
    chanceCreation: 59,
    defensiveRisk: 68,
    transitionRisk: 72,
    setPieceThreat: 48,
    matchControl: 52
  },
  {
    id: "m03",
    date: "2025-08-30",
    competition: "Premier League",
    opponent: "Everton",
    venue: "home",
    goalsFor: 3,
    goalsAgainst: 0,
    result: "win",
    xG: 2.42,
    xGA: 0.62,
    shots: 19,
    shotsOnTarget: 8,
    possession: 61,
    pressingIntensity: 81,
    buildUpQuality: 78,
    chanceCreation: 84,
    defensiveRisk: 25,
    transitionRisk: 30,
    setPieceThreat: 71,
    matchControl: 79
  },
  {
    id: "m04",
    date: "2025-09-13",
    competition: "Champions League",
    opponent: "RB Leipzig",
    venue: "away",
    goalsFor: 2,
    goalsAgainst: 2,
    result: "draw",
    xG: 1.76,
    xGA: 1.58,
    shots: 14,
    shotsOnTarget: 5,
    possession: 51,
    pressingIntensity: 72,
    buildUpQuality: 67,
    chanceCreation: 73,
    defensiveRisk: 58,
    transitionRisk: 64,
    setPieceThreat: 56,
    matchControl: 57
  },
  {
    id: "m05",
    date: "2025-09-20",
    competition: "Premier League",
    opponent: "Chelsea",
    venue: "home",
    goalsFor: 1,
    goalsAgainst: 1,
    result: "draw",
    xG: 1.51,
    xGA: 1.2,
    shots: 13,
    shotsOnTarget: 5,
    possession: 54,
    pressingIntensity: 75,
    buildUpQuality: 72,
    chanceCreation: 68,
    defensiveRisk: 47,
    transitionRisk: 45,
    setPieceThreat: 52,
    matchControl: 63
  },
  {
    id: "m06",
    date: "2025-09-27",
    competition: "Carabao Cup",
    opponent: "Leeds United",
    venue: "home",
    goalsFor: 2,
    goalsAgainst: 0,
    result: "win",
    xG: 1.96,
    xGA: 0.54,
    shots: 17,
    shotsOnTarget: 7,
    possession: 59,
    pressingIntensity: 79,
    buildUpQuality: 74,
    chanceCreation: 78,
    defensiveRisk: 29,
    transitionRisk: 35,
    setPieceThreat: 64,
    matchControl: 73
  },
  {
    id: "m07",
    date: "2025-10-04",
    competition: "Premier League",
    opponent: "Newcastle United",
    venue: "away",
    goalsFor: 0,
    goalsAgainst: 1,
    result: "loss",
    xG: 0.94,
    xGA: 1.38,
    shots: 9,
    shotsOnTarget: 3,
    possession: 48,
    pressingIntensity: 61,
    buildUpQuality: 57,
    chanceCreation: 51,
    defensiveRisk: 70,
    transitionRisk: 69,
    setPieceThreat: 43,
    matchControl: 47
  },
  {
    id: "m08",
    date: "2025-10-18",
    competition: "Champions League",
    opponent: "Inter",
    venue: "home",
    goalsFor: 2,
    goalsAgainst: 1,
    result: "win",
    xG: 1.68,
    xGA: 1.06,
    shots: 12,
    shotsOnTarget: 5,
    possession: 53,
    pressingIntensity: 76,
    buildUpQuality: 71,
    chanceCreation: 70,
    defensiveRisk: 46,
    transitionRisk: 42,
    setPieceThreat: 50,
    matchControl: 64
  },
  {
    id: "m09",
    date: "2025-10-25",
    competition: "Premier League",
    opponent: "Liverpool",
    venue: "away",
    goalsFor: 1,
    goalsAgainst: 3,
    result: "loss",
    xG: 1.12,
    xGA: 2.34,
    shots: 10,
    shotsOnTarget: 4,
    possession: 45,
    pressingIntensity: 58,
    buildUpQuality: 53,
    chanceCreation: 55,
    defensiveRisk: 82,
    transitionRisk: 84,
    setPieceThreat: 45,
    matchControl: 41
  },
  {
    id: "m10",
    date: "2025-11-01",
    competition: "Premier League",
    opponent: "West Ham",
    venue: "home",
    goalsFor: 3,
    goalsAgainst: 1,
    result: "win",
    xG: 2.28,
    xGA: 0.98,
    shots: 18,
    shotsOnTarget: 8,
    possession: 58,
    pressingIntensity: 80,
    buildUpQuality: 77,
    chanceCreation: 82,
    defensiveRisk: 37,
    transitionRisk: 40,
    setPieceThreat: 66,
    matchControl: 76
  },
  {
    id: "m11",
    date: "2025-11-08",
    competition: "FA Cup",
    opponent: "Wolves",
    venue: "away",
    goalsFor: 2,
    goalsAgainst: 0,
    result: "win",
    xG: 1.62,
    xGA: 0.88,
    shots: 13,
    shotsOnTarget: 6,
    possession: 52,
    pressingIntensity: 73,
    buildUpQuality: 68,
    chanceCreation: 71,
    defensiveRisk: 39,
    transitionRisk: 41,
    setPieceThreat: 58,
    matchControl: 61
  },
  {
    id: "m12",
    date: "2025-11-22",
    competition: "Premier League",
    opponent: "Arsenal",
    venue: "home",
    goalsFor: 2,
    goalsAgainst: 2,
    result: "draw",
    xG: 1.84,
    xGA: 1.74,
    shots: 15,
    shotsOnTarget: 6,
    possession: 50,
    pressingIntensity: 71,
    buildUpQuality: 69,
    chanceCreation: 75,
    defensiveRisk: 59,
    transitionRisk: 62,
    setPieceThreat: 61,
    matchControl: 55
  },
  {
    id: "m13",
    date: "2025-11-29",
    competition: "Champions League",
    opponent: "Real Sociedad",
    venue: "away",
    goalsFor: 1,
    goalsAgainst: 1,
    result: "draw",
    xG: 1.3,
    xGA: 1.18,
    shots: 11,
    shotsOnTarget: 4,
    possession: 50,
    pressingIntensity: 68,
    buildUpQuality: 65,
    chanceCreation: 62,
    defensiveRisk: 54,
    transitionRisk: 58,
    setPieceThreat: 49,
    matchControl: 53
  },
  {
    id: "m14",
    date: "2025-12-06",
    competition: "Premier League",
    opponent: "Aston Villa",
    venue: "away",
    goalsFor: 1,
    goalsAgainst: 2,
    result: "loss",
    xG: 1.39,
    xGA: 1.86,
    shots: 12,
    shotsOnTarget: 4,
    possession: 49,
    pressingIntensity: 63,
    buildUpQuality: 60,
    chanceCreation: 61,
    defensiveRisk: 73,
    transitionRisk: 76,
    setPieceThreat: 47,
    matchControl: 48
  },
  {
    id: "m15",
    date: "2025-12-13",
    competition: "Premier League",
    opponent: "Bournemouth",
    venue: "home",
    goalsFor: 4,
    goalsAgainst: 1,
    result: "win",
    xG: 2.74,
    xGA: 0.92,
    shots: 21,
    shotsOnTarget: 10,
    possession: 62,
    pressingIntensity: 84,
    buildUpQuality: 81,
    chanceCreation: 88,
    defensiveRisk: 34,
    transitionRisk: 36,
    setPieceThreat: 69,
    matchControl: 82
  },
  {
    id: "m16",
    date: "2025-12-20",
    competition: "Carabao Cup",
    opponent: "Fulham",
    venue: "away",
    goalsFor: 2,
    goalsAgainst: 1,
    result: "win",
    xG: 1.7,
    xGA: 1.1,
    shots: 14,
    shotsOnTarget: 6,
    possession: 51,
    pressingIntensity: 70,
    buildUpQuality: 66,
    chanceCreation: 69,
    defensiveRisk: 50,
    transitionRisk: 52,
    setPieceThreat: 57,
    matchControl: 56
  },
  {
    id: "m17",
    date: "2025-12-27",
    competition: "Premier League",
    opponent: "Manchester City",
    venue: "away",
    goalsFor: 1,
    goalsAgainst: 2,
    result: "loss",
    xG: 1.18,
    xGA: 2.08,
    shots: 10,
    shotsOnTarget: 3,
    possession: 43,
    pressingIntensity: 59,
    buildUpQuality: 55,
    chanceCreation: 57,
    defensiveRisk: 79,
    transitionRisk: 81,
    setPieceThreat: 46,
    matchControl: 43
  },
  {
    id: "m18",
    date: "2026-01-03",
    competition: "Premier League",
    opponent: "Crystal Palace",
    venue: "home",
    goalsFor: 2,
    goalsAgainst: 0,
    result: "win",
    xG: 1.92,
    xGA: 0.76,
    shots: 16,
    shotsOnTarget: 7,
    possession: 60,
    pressingIntensity: 78,
    buildUpQuality: 76,
    chanceCreation: 79,
    defensiveRisk: 31,
    transitionRisk: 34,
    setPieceThreat: 63,
    matchControl: 75
  },
  {
    id: "m19",
    date: "2026-01-10",
    competition: "FA Cup",
    opponent: "Sunderland",
    venue: "home",
    goalsFor: 3,
    goalsAgainst: 0,
    result: "win",
    xG: 2.21,
    xGA: 0.48,
    shots: 18,
    shotsOnTarget: 9,
    possession: 64,
    pressingIntensity: 82,
    buildUpQuality: 80,
    chanceCreation: 83,
    defensiveRisk: 23,
    transitionRisk: 28,
    setPieceThreat: 72,
    matchControl: 84
  },
  {
    id: "m20",
    date: "2026-01-17",
    competition: "Premier League",
    opponent: "Nottingham Forest",
    venue: "away",
    goalsFor: 2,
    goalsAgainst: 2,
    result: "draw",
    xG: 1.64,
    xGA: 1.66,
    shots: 13,
    shotsOnTarget: 5,
    possession: 52,
    pressingIntensity: 65,
    buildUpQuality: 63,
    chanceCreation: 68,
    defensiveRisk: 66,
    transitionRisk: 70,
    setPieceThreat: 54,
    matchControl: 51
  },
  {
    id: "m21",
    date: "2026-01-24",
    competition: "Champions League",
    opponent: "Atletico Madrid",
    venue: "home",
    goalsFor: 1,
    goalsAgainst: 0,
    result: "win",
    xG: 1.33,
    xGA: 0.84,
    shots: 11,
    shotsOnTarget: 4,
    possession: 55,
    pressingIntensity: 77,
    buildUpQuality: 73,
    chanceCreation: 64,
    defensiveRisk: 36,
    transitionRisk: 39,
    setPieceThreat: 55,
    matchControl: 67
  },
  {
    id: "m22",
    date: "2026-02-01",
    competition: "Premier League",
    opponent: "Brentford",
    venue: "away",
    goalsFor: 2,
    goalsAgainst: 1,
    result: "win",
    xG: 1.88,
    xGA: 1.2,
    shots: 15,
    shotsOnTarget: 6,
    possession: 53,
    pressingIntensity: 72,
    buildUpQuality: 69,
    chanceCreation: 74,
    defensiveRisk: 49,
    transitionRisk: 53,
    setPieceThreat: 60,
    matchControl: 59
  },
  {
    id: "m23",
    date: "2026-02-08",
    competition: "Premier League",
    opponent: "Leicester City",
    venue: "home",
    goalsFor: 3,
    goalsAgainst: 1,
    result: "win",
    xG: 2.36,
    xGA: 0.94,
    shots: 19,
    shotsOnTarget: 8,
    possession: 61,
    pressingIntensity: 83,
    buildUpQuality: 82,
    chanceCreation: 86,
    defensiveRisk: 35,
    transitionRisk: 37,
    setPieceThreat: 68,
    matchControl: 81
  },
  {
    id: "m24",
    date: "2026-02-15",
    competition: "Premier League",
    opponent: "Fulham",
    venue: "away",
    goalsFor: 1,
    goalsAgainst: 1,
    result: "draw",
    xG: 1.42,
    xGA: 1.3,
    shots: 12,
    shotsOnTarget: 4,
    possession: 51,
    pressingIntensity: 67,
    buildUpQuality: 64,
    chanceCreation: 63,
    defensiveRisk: 57,
    transitionRisk: 61,
    setPieceThreat: 51,
    matchControl: 54
  }
];

export const demoFixtures: Fixture[] = [
  {
    id: "f01",
    date: "2026-02-22",
    competition: "Premier League",
    opponent: "West Ham",
    venue: "home",
    opponentForm: 56,
    opponentStrengths: ["Direct transitions", "Set pieces"],
    opponentWeaknesses: ["Space behind full-backs", "Low-block exits"],
    matchImportance: "high"
  },
  {
    id: "f02",
    date: "2026-03-01",
    competition: "Champions League",
    opponent: "Atletico Madrid",
    venue: "away",
    opponentForm: 74,
    opponentStrengths: ["Compact block", "Counter-attacks"],
    opponentWeaknesses: ["Early crosses defended poorly"],
    matchImportance: "critical"
  },
  {
    id: "f03",
    date: "2026-03-08",
    competition: "Premier League",
    opponent: "Wolves",
    venue: "home",
    opponentForm: 48,
    opponentStrengths: ["Wide carries"],
    opponentWeaknesses: ["Chance quality allowed centrally", "Goalkeeper distribution"],
    matchImportance: "medium"
  }
];

export const demoPlayers: PlayerStat[] = [
  {
    id: "p01",
    name: "Bruno Fernandes",
    position: "MF",
    appearances: 24,
    minutes: 2050,
    goals: 9,
    assists: 11,
    xG: 7.6,
    xA: 9.4,
    shots: 58,
    keyPasses: 64,
    rating: 8.35,
    formTrend: "up",
    injuryStatus: "fit",
    pressingActions: 202,
    recoveries: 118
  },
  {
    id: "p02",
    name: "Rasmus Hojlund",
    position: "FW",
    appearances: 22,
    minutes: 1710,
    goals: 12,
    assists: 3,
    xG: 11.2,
    xA: 2.8,
    shots: 53,
    keyPasses: 16,
    rating: 7.82,
    formTrend: "up",
    injuryStatus: "fit",
    pressingActions: 178,
    recoveries: 48
  },
  {
    id: "p03",
    name: "Marcus Rashford",
    position: "FW",
    appearances: 23,
    minutes: 1840,
    goals: 8,
    assists: 5,
    xG: 8.4,
    xA: 4.7,
    shots: 61,
    keyPasses: 33,
    rating: 7.34,
    formTrend: "flat",
    injuryStatus: "monitor",
    pressingActions: 144,
    recoveries: 55
  },
  {
    id: "p04",
    name: "Kobbie Mainoo",
    position: "MF",
    appearances: 21,
    minutes: 1668,
    goals: 3,
    assists: 4,
    xG: 2.4,
    xA: 4.1,
    shots: 24,
    keyPasses: 39,
    rating: 7.58,
    formTrend: "up",
    injuryStatus: "fit",
    pressingActions: 188,
    recoveries: 149
  },
  {
    id: "p05",
    name: "Mason Mount",
    position: "MF",
    appearances: 18,
    minutes: 1120,
    goals: 4,
    assists: 6,
    xG: 3.7,
    xA: 5.3,
    shots: 31,
    keyPasses: 36,
    rating: 7.18,
    formTrend: "up",
    injuryStatus: "fit",
    pressingActions: 152,
    recoveries: 74
  },
  {
    id: "p06",
    name: "Alejandro Garnacho",
    position: "FW",
    appearances: 24,
    minutes: 1580,
    goals: 6,
    assists: 7,
    xG: 6.1,
    xA: 5.9,
    shots: 49,
    keyPasses: 41,
    rating: 7.27,
    formTrend: "flat",
    injuryStatus: "fit",
    pressingActions: 165,
    recoveries: 62
  },
  {
    id: "p07",
    name: "Diogo Dalot",
    position: "DF",
    appearances: 23,
    minutes: 1990,
    goals: 2,
    assists: 5,
    xG: 1.5,
    xA: 4.8,
    shots: 20,
    keyPasses: 43,
    rating: 7.21,
    formTrend: "flat",
    injuryStatus: "fit",
    pressingActions: 156,
    recoveries: 151
  },
  {
    id: "p08",
    name: "Lisandro Martinez",
    position: "DF",
    appearances: 19,
    minutes: 1610,
    goals: 1,
    assists: 2,
    xG: 0.9,
    xA: 1.7,
    shots: 11,
    keyPasses: 18,
    rating: 7.08,
    formTrend: "down",
    injuryStatus: "monitor",
    pressingActions: 112,
    recoveries: 138
  },
  {
    id: "p09",
    name: "Andre Onana",
    position: "GK",
    appearances: 24,
    minutes: 2160,
    goals: 0,
    assists: 0,
    xG: 0,
    xA: 0.2,
    shots: 0,
    keyPasses: 5,
    rating: 7.02,
    formTrend: "up",
    injuryStatus: "fit",
    pressingActions: 0,
    recoveries: 34
  }
];

export const automationCards = [
  ["Щотижневий звіт", "готово", "Останній запуск: Пн, 16 лют, 09:00"],
  ["Підготовка до матчу", "заплановано", "Наступний запуск: Нд, 22 лют, 08:30"],
  ["Сповіщення про аномалії", "виконано", "Останній запуск: сьогодні, 10:15"],
  ["Демо-сценарій", "очікує запуску", "Наступний запуск: Пт, 27 лют, 16:42"]
] as const;
